include_recipe 'workstation::chef_solo'
include_recipe 'workstation::chef_dk'
include_recipe 'workstation::update'
include_recipe 'workstation::git'
include_recipe 'workstation::rvm'
include_recipe 'workstation::ntp'
include_recipe 'workstation::xfce'
include_recipe 'workstation::rdp'
# include_recipe 'workstation::rubymine'