chef_server_url                  'http://127.0.0.1:8889'
chef_zero.enabled                true
chef_zero.port                   '8889'
client_key                       '/etc/chef/client.pem'
client_registration_retries      5
cookbook_path                    '/var/chef/cookbooks'
cookbook_sync_threads            1
data_bag_decrypt_minimum_version 2
data_bag_path                    '/var/chef/data_bags'
diff_disabled                    false
diff_filesize_threshold          10000000
diff_output_threshold            1000000
enable_reporting                 false
enable_reporting_url_fatals      false
environment                      'deploy'
environment_path                 '/var/chef/environments'
file_atomic_update               true
file_backup_path                 '/var/chef/backup'
file_cache_path                  '/var/chef/cache'
file_staging_uses_destdir        true
group                            'root' #TODO change this to the chef group once we have a working vm.
interval                         1800
listen                           true
local_key_generation             true
local_mode                       true
log_level                        :info
log_location                     Chef::Log::Syslog.new('chef-client', ::Syslog::LOG_DAEMON)
no_lazy_load                     true
#node_name                        'student'
node_path                        '/var/chef/node'
rest_timeout                     300
role_path                        '/var/chef/roles'
user                             'root'
